### ISSUE TITLE
Consider statically linking OpenSSL into erts 

### ISSUE THREAD

**Issue by starbelly** [jelly-beam/otp-macos#4]
We have the ability to statically link libs to erts, such as openssl. While this may have some neat security properties, it's more about less fragility in runners. That is to say if we install, build, and link in libraries users won't have to worry about something breaking underneath them. 

Currently, and as part of the initial work, we're depending on brew to install openssl. This also means, that users will have to use brew to install openssl. This can be fragile. 

At the very least we could build openssl ourselves and bundle it, but static linking sounds like the way to go IMHO.

**Comment by paulo-ferraz-oliveira** [comment]
> This also means, that users will have to use brew to install openssl.

Wdym, for self-hosted runners?

What about other stuff that Erlang depends on (like `zlib` and whatnot). Do we need to make similar considerations?

**Comment by paulo-ferraz-oliveira** [comment]
Consider this, too: https://rentzsch.tumblr.com/post/33696323211/wherein-i-write-apples-technote-about-openssl-on.

**Comment by starbelly** [comment]
Yeah, so there's another consideration to make... if we statically link and include openssl and others as part of the build, we're removing the option for users to test with other versions.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... we could have a "no-ssl" variant, but that opens the door for having variants for all sorts of configuration options, right(?)

Look at what `bob` does: https://github.com/hexpm/bob/blob/main/priv/scripts/otp/build_otp_ubuntu.sh#L23. This was a part of my "sources for inspiration" since we're using it with success in `setup-beam` (one of our use cases) and nobody's had a **real** issue with it yet.

In any case, we have a process in this repo. and it's open. If you wanna fork it and change the options, you can, too 😄. At that moment, though, if lots of people request it, we could "simply" update the code so that taking "hooks" into account would be feasible.

In my local OTP builds, for example, I do:

```
KERL_CONFIGURE_OPTIONS=
KERL_CONFIGURE_OPTIONS="$KERL_CONFIGURE_OPTIONS --disable-dynamic-ssl-lib"
KERL_CONFIGURE_OPTIONS="$KERL_CONFIGURE_OPTIONS --with-ssl=..."
```

which is similar to what you might be proposing. Let's make a decision, document it properly, and implement it. 👍

**Comment by paulo-ferraz-oliveira** [comment]
I change the title to reflect the fact we should only care about `openssl` for the time being. If the time comes to care for other options (in the future) we may have to consider how we'll version the release files (e.g. with a suffix) since changing compilation options can break stuff for consumers, considering these aren't going through something like `setup-beam` which is my first real use case.
