### ISSUE TITLE
Release artifact naming convention

### ISSUE THREAD

**Issue by starbelly** [jelly-beam/otp-macos#8]
I notice we're including the matrix version, but I'm not sure why. 

Also, per #7 it followed this convention, but I feel like this should just be `sha256.txt`

**Comment by paulo-ferraz-oliveira** [comment]
> including the matrix version

What do you mean, the macOS version? I guess because I imagined small differences in the OS might lead to breakage if e.g. we just do this for 11 and expect it to work in 12, and 13. This way we're "more sure" it'll work properly.

Also, circling back to the discussion about vendoring in, the runners are something we don't control, so there's also the issue that these might reveal problems when internally bumping stuff in macOS 11 vs 12, for example...

**Comment by starbelly** [comment]
I see. As for the sha256 file, do you think it should follow the same convention?

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I've recently updated it to follow the same convention, so it's bundled next to the `.tar.gz`. If you feel your initial concerns are addressed feel free to close this. Otherwise lemme know if my reasoning is no good 😄 and then we can probably have a single .tar.gz for the bundle.
